export default {
  Category: require('images/Category.png'),
  CategoryBold: require('images/CategoryBold.png'),
  Home: require('images/Home.png'),
  HomeBold: require('images/HomeBold.png'),
  MenuIcon: require('images/Menu.png'),
  NoImage: require('images/NoImage.png'),
  Search: require('images/Search.png'),
  User: require('images/User.png'),
  Up: require('images/Up.png'),
  Down: require('images/Down.png'),
  Eye: require('images/Eye.png'),
  EyeGray: require('images/EyeGray.png'),
  TabBar: {
    Home: require('images/Home.png'),
    Category: require('images/Category.png'),
    Search: require('images/Search.png'),
    User: require('images/Signin.png'),
  },

  Check: require('images/Check.png'),
  MoMo: require('images/MoMo.png'),
  Cart: require('images/Cart.png'),
  VNPay: require('images/VNPay.png'),
  DrapDropIcon: require('images/DrapDropIcon.png'),
  ArrowLeft: require('images/ArrowLeft.png'),
  ArrowRight: require('images/ArrowRight.png'),
  ZaloPay: require('images/ZaloPay.png'),
  QRCode: require('images/QRCode.jpeg'),
  Withdraw: require('images/Withdraw.png'),
  Edit: require('images/Edit.png'),
  Register: {
    phone_1: require('images/register/phone-1.png'),
  },
  WidthDraw: {
    Done: require('images/Done.png'),
    Plus: require('images/Plus+.png'),
    Close: require('images/Close.png'),
  },
  Logo: require('images/Logo.png'),
  Noti: require('images/Noti.png'),
  Avatar: require('images/Avatar.jpg'),
  Homes: {
    BgHeader: require('images/home/BgHeader.jpg'),
    NapViTuDong: require('images/home/NapViTuDong.png'),
    ThanhToanGt: require('images/home/ThanhToanGt.png'),
    DichVuGt: require('images/home/DichVuGt.png'),
    DanhSachXe: require('images/home/DanhSachXe.png'),
    MuaVe: require('images/home/MuaVe.png'),
    LichSuXe: require('images/home/LichSuXe.png'),
    TramDichvVu: require('images/home/TramDichvVu.png'),
    Banner: require('images/home/Banner.png'),
    NapTien: require('images/home/NapTien.png'),
    RutTien: require('images/home/RutTien.png'),
    QAPAY: require('images/home/QAPAY.png'),
    ChuyenTien: require('images/home/ChuyenTien.png'),
    NapTien: require('images/home/NapTien.png'),
  },
  Profile: {
    SoDu: require('images/profile/SoDu.png'),
    Bank: require('images/profile/Bank.png'),
    BaoMat: require('images/profile/BaoMat.png'),
    Edit: require('images/profile/Edit.png'),
    Help: require('images/profile/Help.png'),
    Location: require('images/profile/Location.png'),
    Logout: require('images/profile/Logout.png'),
    MaThanhToan: require('images/profile/MaThanhToan.png'),
    ThanhToan: require('images/profile/ThanhToan.png'),
    Translate: require('images/profile/Translate.png'),
  },
};
