export default {
  Category: require('images/Category.png'),
  CategoryBold: require('images/CategoryBold.png'),
  Home: require('images/Home.png'),
  HomeBold: require('images/HomeBold.png'),
  MenuIcon: require('images/Menu.png'),
  NoImage: require('images/NoImage.png'),
  Search: require('images/Search.png'),
  User: require('images/User.png'),
  Up: require('images/Up.png'),
  Down: require('images/Down.png'),
  Right: require('images/right.png'),
  Eye: require('images/Eye.png'),
  EyeGray: require('images/EyeGray.png'),
  DefaultUser: require('images/default_user.png'),
  Splash: require('images/Splash.png'),
  Background: require('images/Background.png'),
  BgModal: require('images/bgModal.png'),
  TabBar: {
    Home: require('images/tabBar/home.png'),
    HomeGray: require('images/tabBar/HomeGray.png'),
    Category: require('images/Category.png'),
    Search: require('images/Search.png'),
    User: require('images/tabBar/user.png'),
    BottomTab: require('images/tabBar/BottomTab.png'),
    QR: require('images/tabBar/QR.png'),
    test: require('images/tabBar/test.gif'),
  },

  Check: require('images/Check.png'),
  MoMo: require('images/MoMo.png'),
  Cart: require('images/Cart.png'),
  VNPay: require('images/VNPay.png'),
  DrapDropIcon: require('images/DrapDropIcon.png'),
  ArrowLeft: require('images/ArrowLeft.png'),
  ArrowRight: require('images/ArrowRight.png'),
  ZaloPay: require('images/ZaloPay.png'),
  QRCode: require('images/QRCode.jpeg'),
  Withdraw: require('images/Withdraw.png'),
  Edit: require('images/Edit.png'),
  Phone: require('images/phone.png'),
  Register: {
    Info: require('images/Info.png'),
  },
  WidthDraw: {
    Done: require('images/Done.png'),
    Plus: require('images/Plus+.png'),
    Close: require('images/Close.png'),
  },
  Logo: require('images/Logo.png'),
  Noti: require('images/Noti.png'),
  Avatar: require('images/Avatar.jpg'),
  Homes: {
    BgHeader: require('images/home/BgHeader.jpg'),
    NapViTuDong: require('images/home/NapViTuDong.png'),
    ThanhToanGt: require('images/home/ThanhToanGt.png'),
    DichVuGt: require('images/home/DichVuGt.png'),
    DanhSachXe: require('images/home/DanhSachXe.png'),
    MuaVe: require('images/home/MuaVe.png'),
    LichSuXe: require('images/home/LichSuXe.png'),
    TramDichvVu: require('images/home/TramDichvVu.png'),
    Banner: require('images/home/Banner.png'),
    NapTien: require('images/home/NapTien.png'),
    RutTien: require('images/home/RutTien.png'),
    QAPAY: require('images/home/QAPAY.png'),
    ChuyenTien: require('images/home/ChuyenTien.png'),
    LichSuGd: require('images/home/LichSuGd.png'),
    Wave: require('images/home/wave.jpg'),
    Avatar: require('images/home/avatar.png'),
    Arrow: require('images/home/CircleRight.png'),
    SanBay: require('images/home/sanBay.png'),
    YTe: require('images/home/yTe.png'),
    BaoHiem: require('images/home/baoHiem.png'),
    GiaoThong: require('images/home/giaoThong.png'),
  },
  Transfer: {
    Ellipse: require('images/Ellipse.png'),
    Rectangle: require('images/Rectangle.png'),
    Bank: require('images/bank.png'),
    ArrowRight: require('images/arrow-right.png'),
    Mobile: require('images/mobile.png'),
    User_1: require('images/user/user1.png'),
    User_2: require('images/user/user2.png'),
    User_3: require('images/user/user3.png'),
    User_4: require('images/user/user4.png'),
    EmptyWallet: require('images/empty-wallet.png'),
    ArrowCircleDown: require('images/arrow-circle-down.png'),
    VIETCOMBANK: require('images/vietcombank.png'),
    VIETTINBANK: require('images/viettinbank.png'),
    EXIMBANK: require('images/eximbank.png'),
    UNION: require('images/Union.png'),
    Background: require('images/LogoBG.png'),
    Lock: require('images/Lock.png'),
    CloseCircle: require('images/close-circle.png'),
  },
  Profile: {
    SoDu: require('images/profile/SoDu.png'),
    Bank: require('images/profile/Bank.png'),
    BaoMat: require('images/profile/BaoMat.png'),
    Edit: require('images/profile/Edit.png'),
    Help: require('images/profile/Help.png'),
    Location: require('images/profile/Location.png'),
    Logout: require('images/profile/Logout.png'),
    MaThanhToan: require('images/profile/MaThanhToan.png'),
    ThanhToan: require('images/profile/ThanhToan.png'),
    Translate: require('images/profile/Translate.png'),
  },
  ConnectBank: {
    logoAgribank: require('images/logo-bank/logo-1.png'),
    logoBidv: require('images/logo-bank/logo-2.png'),
    logoVcb: require('images/logo-bank/logo-3.png'),
    logoVtb: require('images/logo-bank/logo-4.png'),
    logoExb: require('images/logo-bank/logo-5.png'),
    logoHdb: require('images/logo-bank/logo-6.png'),
    logoMbb: require('images/logo-bank/logo-7.png'),
    logoScob: require('images/logo-bank/logo-8.png'),
    logoScb: require('images/logo-bank/logo-9.png'),
    logoVbb: require('images/logo-bank/logo-10.png'),
    logoShb: require('images/logo-bank/logo-11.png'),
    logoTpb: require('images/logo-bank/logo-12.png'),
    //------------
    Deposit: require('images/icons/deposit.png'),
    Withdraw: require('images/icons/withdraw.png'),
    Exchange: require('images/icons/exchange.png'),
    Plus: require('images/icons/add.png'),
    Search: require('images/icons/search-normal.png'),
  },
  Bank: {
    Vietinbank: require('images/bank/Vietinbank.png'),
    Eximbank: require('images/bank/Eximbank.png'),
    Vietcombank: require('images/bank/Vietcombank.png'),
    Plus: require('images/bank/Plus.png'),
  },
  logoEpay: require('images/logo-epay.png'),
  Phone_1: require('images/phone-1.png'),
  SignIn: {
    FingerPrint: require('images/icons/fingerprint.png'),
    Face: require('images/icons/face.png'),
  },
  SignUp: {
    BgBlue: require('images/bg-blue.png'),
    BigPhone: require('images/icons/big-phone.png'),
    BlueWave: require('images/bg/blue-wave.png'),
    TouchId: require('images/icons/touch-id.png'),
  },
  Kyc: {
    Calendar: require('images/icons/calendar.png'),
    Wave: require('images/icons/wave-2.png'),
    Test: require('images/icons/test.png'),
    BigCircle: require('images/icons/big-circle.png'),
    SpecialArrow: require('images/icons/special-arrow.png'),
  },
  VerifyUserInfo: {
    iconDown: require('images/icons/down.png'),
    camera: require('images/icons/camera.png'),
    wave: require('images/icons/wave.png'),
    tick: require('images/icons/tick.png'),
    topLeftAngle: require('images/icons/angle-1.png'),
    topRightAngle: require('images/icons/angle-2.png'),
    botLeftAngle: require('images/icons/angle-3.png'),
    botRightAngle: require('images/icons/angle-4.png'),
    cmndBlur: require('images/identity-card/cmnd-blur.png'),
    cmndDark: require('images/identity-card/cmnd-dark.png'),
    cmndFail: require('images/identity-card/cmnd-fail.png'),
    IdFront: require('images/identity-card/Front.png'),
    IdBack: require('images/identity-card/Back.png'),
    Passport: require('images/identity-card/Passport.png'),
  },
  TransactionHistory: {
    filter: require('images/icons/filter.png'),
    CardTick: require('images/icons/card-tick.png'),
    Success: require('images/icons/success.png'),
    Fail: require('images/icons/fail.png'),
    LogoBg: require('images/LogoBG.png'),
  },
  Capture: require('images/Capture.png'),
  Camera: {
    TopLeft: require('images/camera/TopLeft.png'),
    TopRight: require('images/camera/TopRight.png'),
    BottomLeft: require('images/camera/BottomLeft.png'),
    BottomRight: require('images/camera/BottomRight.png'),
    Oval: require('images/camera/oval.png'),
    CameraSquare: require('images/camera/CameraSquare.png'),
    ScanQR: require('images/camera/ScanQR.png'),
    Flash: require('images/camera/Flash.png'),
    QR: require('images/camera/QR.png'),
    Scan: require('images/camera/Scan.png'),
    Gallery: require('images/camera/Gallery.png'),
  },
  Modal: {
    Camera: require('images/modal/camera.png'),
    Lock: require('images/modal/lock.png'),
    UserTick: require('images/modal/userTick.png'),
  },
  warning: require('images/ic_warning.png'),
  primaryButton: require('images/Button.png'),
};
