const ASYNC_STORAGE_KEY = {
  USER: {
    PHONE: 'PHONE',
    PASSWORD_ENCRYPTED: 'PASSWORD_ENCRYPTED',
    TOUCHID_ENABLED: 'TOUCHID_ENABLED',
    TOKEN: 'TOKEN',
  },
  COMMON: {
    SMART_OTP_DISABLED: 'SMART_OTP_DISABLED',
    FIRST_OPEN_APP: 'FIRST_OPEN_APP',
  },
  LANGUAGE: {
    CURRENT_LANGUAGE: 'CURRENT_LANGUAGE',
  },
};
export default ASYNC_STORAGE_KEY;
