const ASYNC_STORAGE_KEY = {
  USER: {
    PHONE: 'PHONE',
    PASSWORD_ENCRYPTED: 'PASSWORD_ENCRYPTED',
    TOUCHID_ENABLED: 'TOUCHID_ENABLED',
    TOKEN: 'TOKEN',
  },
};
export default ASYNC_STORAGE_KEY;
