const SCREEN = {
  HOME: 'Home',
  AUTH: 'Auth',
  LOGIN: 'Login',
  REGISTER: 'Register',
  FORGET_PASSWORD: 'ForgetPassword',
  REGISTER_PASSWORD: 'RegisterPassword',
  REGISTER_NAME: 'RegisterName',
  OTP: 'OTP',
  BANK: 'Bank',
  NOTIFICATION: 'Notification',
  TOP_UP: 'TopUp',
  WITHDRAW: 'Withdraw',
  QRPAY: 'QRPay',
  TRANSFER: 'Transfer',
  TRAFFIC_FEE: 'TrafficFee',
  TRAFFIC_VIOLATION_PAYMENT: 'TrafficViolationPayment',
  CONFIRMATION: 'Confirmation',
  USER: 'User',
  HOME: 'Home',
  TRANSACTION: 'Transaction',
  TAB_NAVIGATION: 'TabNavigation',
  CHANGE_PASSWORD: 'ChangePassword',
  SECURITY: 'Security',
  USER_INFO: 'UserInfo',
  PAYMENT_SETTINGS: 'PaymentSettings',
  LIMIT_SETTING: 'LimitSetting',
  EDIT_INFO: 'EditInfo',
  NEW_PASSWORD: 'NewPassword',
  CONTACTS: 'Contacts',
  VERIFY_USER_INFO: 'VerifyUserInfo',
  VERIFY_IDENTITY_CARD: 'VerifyIdentityCard',
  VERIFY_USER_PORTRAIT: 'VerifyUserPortrait',
  CHECKOUT_SUCCESS: 'CheckoutSuccess',
  CHECKOUT_FAILURE: 'CheckoutFailure',
};
export default SCREEN;
