const TERM_TYPE = {
  ACTIVE_SMART_OTP: 1,
  REGISTER_ACCOUNT: 2,
  UPLOAD_PICTURE_REGISTER: 3,
  UPLOAD_PICTURE_CHANGE_INFO: 4,
  TRANSFER_MONEY: 5,
  REGISTER_TOLL: 6,
  PAYMENT_TOLL: 7,
  PAYMENT: 8,
  AUTO_CASHIN: 9,
};
export default TERM_TYPE;
