const TEXT = {
  SEARCH_PLACEHOLDER: 'Nhập từ khoá tìm kiếm',
  ALL: 'Tất cả',
  HOME: 'Trang chủ',
  CATEGORY: 'Danh mục',
  SEARCH: 'Tìm kiếm',
  USER: 'Cá nhân',
  SORT: 'Sắp xếp',
  SUGGESTION: 'Danh mục gợi ý',
  CATEGORY_LIST: 'Danh mục khoá học',
  COMMENT_PLACEHOLDER: 'Nhập bình luận…',
  ANSWER_PLACEHOLDER: 'Nhập câu trả lời',
  ANSWER_WARNING: 'Hãy trả lời hết các câu hỏi bạn nhé!',
  ANSWER: 'Đáp án',
  RESULT: 'Kết quả',
  BACK: 'Quay lại',
  AGAIN: 'Làm lại',
  SUBMIT: 'Nộp bài',
  COURSE: 'Khoá học',
  MEMBER: 'học viên',
  COURSE_DETAIL: 'Chi tiết khoá học ',
  MORE_TEXT: 'Xem thêm',
  RELATED_COURSE: 'Khóa học liên quan',
  WARNING_DOCUMMENT: 'Khoá học chưa có tài liệu!',
  ALERT: 'Thông báo',
  CONFIRM: 'Xác nhận',
  CONFIRM_LOGOUT: 'Bạn có chắc chắn muốn đăng xuất?',
  LOGOUT: ' Đăng xuất',
  ERROR: 'Lỗi',
  ERROR_REMOVE_COURSE: 'Đã xảy ra lỗi khi xóa khóa học.',
  MY_COURSES: 'Khoá học của tôi',
  CONTACT_US: 'Liên hệ với chúng tôi',
  LOGIN_EMAIL: 'Đăng nhập bằng địa chỉ Email',
  INCOMPLETED_COURSES: 'Khóa học sắp hoàn thành',
  COMPLETED_COURSES: 'Khóa học đã hoàn thành',
  PURCHASED_COURSES: 'Khóa học đã mua',
  SAVED_COURSES: 'Khóa học đã lưu',
  SAVE: 'Lưu',
  SAVED: 'Đã lưu',
  SAVE_SUCCESS: 'Lưu thành công!',
  EDIT_INFO: 'Chỉnh sửa thông tin',
  FIRST_NAME: 'Họ',
  LAST_NAME: 'Tên',
  NAME_PLACEHODLE: 'Nhập tên của bạn',
  EMAIL_PLACEHODLE: 'Nhập email của bạn',
  ADDRESS: 'Địa chỉ',
  PHONE: 'Số điện thoại',
  UPDATE_SUCCESS: 'Cập nhật thành công!',
  AUTHOR: 'Người viết',
  UPDATE_DATE: 'Ngày cập nhật',
  CORRECT_ANSWER: 'Số câu trả lời đúng',
  TIME: 'Thời gian',
  POINT: 'Điểm số',
  CONFIRM_REMOVE: 'Bạn có chắc muốn xóa khóa học?',
  VIEW_DOCUMENT: ' Xem tài liệu',
  VIEW_CONTENT: 'Xem nội dung',
  COURSE_CONTENT: 'Nội dung khoá học',
  COURSE_INTRODUCT: 'Giới thiệu khoá học',
  EXPERT: 'Chuyên gia',
  DONE: 'Xong',
  COURSE_ALREADY_SAVED: 'Khoá học đã được lưu!',
  ALREADY_IN_CART: 'Khóa học hiện đã có trong giỏ hàng!',
  PAY_NOW: 'Mua ngay',
  CONTENT: 'Nội dung',
  DOCUMENT: 'Tài liệu',
  USERNAME_NOT_BLANK: 'Tên đăng nhập không được bỏ trống',
  PASSWORD: 'Mật khẩu',
  PASSWORD_NOT_BLANK: 'Mật khẩu không được bỏ trống',
  PASSWORD_MIN_8: 'Mật khẩu phải tối thiểu 8 ký tự',
  PASSWORD_NOT_MATCH: 'Mật khẩu không khớp',
  EMAIL_INVALID: 'Email không hợp lệ',
  EMAIL_NOT_BLANK: 'Email không được bỏ trống',
  PHONE_INVALID: 'Số điện thoại không hợp lệ',
  AGREEMENT_NOT_ACCEPTED:
    'Bạn cần chấp nhận điều khoản sử dụng để đăng ký tài khoản',
  LECTURER: 'Giảng viên khoá học',
  WRITE_REVIEW: 'Viết đánh giá',
  REVIEWS: 'đánh giá',
  REVIEWS_TITLE: 'Phản hồi về khoá học',
  REVIEWS_QUESTION: 'Bạn cảm thấy khóa học này như thế nào? ',
  REVIEWS_PLACEHODLE: 'Viết cảm nhận của bạn về khóa học này',
  SAVE_INFO: 'Lưu tên, email cho lần nhập tiếp theo',
  TRANSACTION_HISTORY: 'Lịch sử giao dịch',
  PROFILE: 'Profile',
};
export default TEXT;
